-- Registry privado do Hermes e da fila de hipóteses do Laboratório Automatizado.
-- V1 é somente monitoramento e revisão humana; não inicia execuções.

create table if not exists lab_automatizado.agents (
  agent_key text primary key,
  display_name text not null,
  agent_type text not null check (agent_type in ('hermes')),
  status text not null default 'offline' check (status in (
    'offline', 'starting', 'idle', 'observing', 'proposing', 'reviewing',
    'degraded', 'error'
  )),
  mode text not null default 'disabled' check (mode in (
    'disabled', 'observation', 'proposal', 'controlled_execution'
  )),
  version text,
  capabilities jsonb not null default '[]'::jsonb,
  last_heartbeat_at timestamptz,
  last_activity_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lab_automatizado.hypotheses (
  id uuid primary key default gen_random_uuid(),
  hypothesis_key text not null unique,
  agent_key text not null references lab_automatizado.agents(agent_key),
  asset text check (asset is null or asset in ('WDOFUT', 'WINFUT')),
  family text not null check (family in ('entry', 'exit', 'portfolio', 'market_structure')),
  title text not null,
  summary text not null,
  observation text,
  mechanism text,
  status text not null default 'proposed' check (status in (
    'proposed', 'under_review', 'approved_for_test', 'rejected', 'archived'
  )),
  payload jsonb not null default '{}'::jsonb,
  source_run_id uuid references lab_automatizado.runs(id),
  requested_by text,
  reviewed_by text,
  review_notes text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lab_automatizado.agent_events (
  id bigint generated by default as identity primary key,
  agent_key text not null references lab_automatizado.agents(agent_key),
  event_type text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agents_status_idx
  on lab_automatizado.agents (status, last_heartbeat_at desc);

create index if not exists hypotheses_status_created_idx
  on lab_automatizado.hypotheses (status, created_at desc);

create index if not exists hypotheses_agent_created_idx
  on lab_automatizado.hypotheses (agent_key, created_at desc);

create index if not exists agent_events_agent_created_idx
  on lab_automatizado.agent_events (agent_key, created_at desc);

drop trigger if exists agents_set_updated_at on lab_automatizado.agents;
create trigger agents_set_updated_at
before update on lab_automatizado.agents
for each row execute function lab_automatizado.set_updated_at();

drop trigger if exists hypotheses_set_updated_at on lab_automatizado.hypotheses;
create trigger hypotheses_set_updated_at
before update on lab_automatizado.hypotheses
for each row execute function lab_automatizado.set_updated_at();

alter table lab_automatizado.agents enable row level security;
alter table lab_automatizado.hypotheses enable row level security;
alter table lab_automatizado.agent_events enable row level security;

revoke all on lab_automatizado.agents from public, anon, authenticated;
revoke all on lab_automatizado.hypotheses from public, anon, authenticated;
revoke all on lab_automatizado.agent_events from public, anon, authenticated;
grant select, insert, update, delete on lab_automatizado.agents to service_role;
grant select, insert, update, delete on lab_automatizado.hypotheses to service_role;
grant select, insert, update, delete on lab_automatizado.agent_events to service_role;
grant usage, select on all sequences in schema lab_automatizado to service_role;

comment on table lab_automatizado.agents is 'Estado e capacidades dos agentes deste laboratório.';
comment on table lab_automatizado.hypotheses is 'Registry versionado de hipóteses propostas e revisadas.';
comment on table lab_automatizado.agent_events is 'Log append-only de atividade dos agentes.';

create or replace function public.lab_automatizado_list_agents()
returns setof lab_automatizado.agents
language sql
security definer
set search_path = pg_catalog, public, lab_automatizado
as $$
  select *
    from lab_automatizado.agents
   order by case when status = 'error' then 0 when status = 'offline' then 1 else 2 end,
            coalesce(last_activity_at, last_heartbeat_at, created_at) desc;
$$;

create or replace function public.lab_automatizado_list_hypotheses(p_limit integer default 50)
returns setof lab_automatizado.hypotheses
language sql
security definer
set search_path = pg_catalog, public, lab_automatizado
as $$
  select *
    from lab_automatizado.hypotheses
   order by created_at desc
   limit least(greatest(coalesce(p_limit, 50), 1), 100);
$$;

create or replace function public.lab_automatizado_review_hypothesis(
  p_hypothesis_id uuid,
  p_status text,
  p_review_notes text,
  p_reviewed_by text
)
returns lab_automatizado.hypotheses
language plpgsql
security definer
set search_path = pg_catalog, public, lab_automatizado
as $$
declare
  v_hypothesis lab_automatizado.hypotheses;
begin
  if p_status not in ('under_review', 'approved_for_test', 'rejected', 'archived') then
    raise exception 'hypothesis_status_not_allowed';
  end if;

  update lab_automatizado.hypotheses
     set status = p_status,
         review_notes = nullif(trim(coalesce(p_review_notes, '')), ''),
         reviewed_by = nullif(trim(coalesce(p_reviewed_by, '')), ''),
         reviewed_at = now(),
         updated_at = now()
   where id = p_hypothesis_id
     and status not in ('archived', 'rejected')
   returning * into v_hypothesis;

  if v_hypothesis.id is null then
    raise exception 'hypothesis_not_reviewable';
  end if;

  insert into lab_automatizado.agent_events (agent_key, event_type, message, payload)
  values (
    v_hypothesis.agent_key,
    'hypothesis_reviewed',
    'Hipótese revisada no painel.',
    jsonb_build_object(
      'hypothesis_id', v_hypothesis.id,
      'hypothesis_key', v_hypothesis.hypothesis_key,
      'status', p_status,
      'reviewed_by', p_reviewed_by
    )
  );

  return v_hypothesis;
end;
$$;

create or replace function public.lab_automatizado_heartbeat_agent(
  p_agent_key text,
  p_status text,
  p_mode text,
  p_version text,
  p_capabilities jsonb,
  p_metadata jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, lab_automatizado
as $$
begin
  if p_status not in ('offline', 'starting', 'idle', 'observing', 'proposing', 'reviewing', 'degraded', 'error') then
    raise exception 'agent_status_not_allowed';
  end if;
  if p_mode not in ('disabled', 'observation', 'proposal', 'controlled_execution') then
    raise exception 'agent_mode_not_allowed';
  end if;

  update lab_automatizado.agents
     set status = p_status,
         mode = p_mode,
         version = p_version,
         capabilities = coalesce(p_capabilities, '[]'::jsonb),
         metadata = coalesce(p_metadata, '{}'::jsonb),
         last_heartbeat_at = now(),
         last_activity_at = now(),
         updated_at = now()
   where agent_key = p_agent_key;

  if not found then
    raise exception 'agent_not_registered';
  end if;
end;
$$;

create or replace function public.lab_automatizado_record_hypothesis(
  p_hypothesis_key text,
  p_agent_key text,
  p_asset text,
  p_family text,
  p_title text,
  p_summary text,
  p_observation text,
  p_mechanism text,
  p_payload jsonb,
  p_source_run_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, lab_automatizado
as $$
declare
  v_id uuid;
begin
  insert into lab_automatizado.hypotheses (
    hypothesis_key, agent_key, asset, family, title, summary,
    observation, mechanism, payload, source_run_id
  ) values (
    p_hypothesis_key, p_agent_key, p_asset, p_family, p_title, p_summary,
    p_observation, p_mechanism, coalesce(p_payload, '{}'::jsonb), p_source_run_id
  )
  returning id into v_id;

  insert into lab_automatizado.agent_events (agent_key, event_type, message, payload)
  values (
    p_agent_key,
    'hypothesis_proposed',
    'Nova hipótese registrada.',
    jsonb_build_object('hypothesis_id', v_id, 'hypothesis_key', p_hypothesis_key)
  );

  return v_id;
end;
$$;

revoke all on function public.lab_automatizado_list_agents() from public, anon, authenticated;
revoke all on function public.lab_automatizado_list_hypotheses(integer) from public, anon, authenticated;
revoke all on function public.lab_automatizado_review_hypothesis(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.lab_automatizado_heartbeat_agent(text, text, text, text, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.lab_automatizado_record_hypothesis(text, text, text, text, text, text, text, text, jsonb, uuid) from public, anon, authenticated;

grant execute on function public.lab_automatizado_list_agents() to service_role;
grant execute on function public.lab_automatizado_list_hypotheses(integer) to service_role;
grant execute on function public.lab_automatizado_review_hypothesis(uuid, text, text, text) to service_role;
grant execute on function public.lab_automatizado_heartbeat_agent(text, text, text, text, jsonb, jsonb) to service_role;
grant execute on function public.lab_automatizado_record_hypothesis(text, text, text, text, text, text, text, text, jsonb, uuid) to service_role;

insert into lab_automatizado.agents (
  agent_key, display_name, agent_type, status, mode, capabilities, metadata
) values (
  'hermes-supervisor',
  'Hermes Research Supervisor',
  'hermes',
  'offline',
  'disabled',
  '["read_development_data", "propose_hypotheses", "adversarial_review"]'::jsonb,
  '{"panel_v1": true, "autonomous_execution": false}'::jsonb
)
on conflict (agent_key) do nothing;
