-- Control plane exclusivo do Laboratório Automatizado.
-- Não armazena ticks nem Parquets; registra comandos, execuções e artefatos.

create schema if not exists lab_automatizado;

create or replace function lab_automatizado.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists lab_automatizado.runs (
  id uuid primary key default gen_random_uuid(),
  run_key text not null unique,
  run_type text not null check (run_type in ('quality_benchmark', 'research')),
  status text not null default 'queued' check (status in (
    'queued', 'claimed', 'running', 'succeeded', 'failed',
    'cancel_requested', 'cancelled'
  )),
  dataset_manifest text,
  config jsonb not null default '{}'::jsonb,
  requested_by text,
  worker_id text,
  error_message text,
  heartbeat_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists lab_automatizado.commands (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references lab_automatizado.runs(id) on delete cascade,
  command_type text not null check (command_type in ('start_run', 'cancel_run')),
  status text not null default 'queued' check (status in (
    'queued', 'claimed', 'completed', 'failed', 'cancelled'
  )),
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  requested_by text,
  claimed_by text,
  error_message text,
  requested_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz
);

create table if not exists lab_automatizado.events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references lab_automatizado.runs(id) on delete cascade,
  event_type text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists lab_automatizado.artifacts (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references lab_automatizado.runs(id) on delete cascade,
  artifact_type text not null,
  uri text not null,
  sha256 text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists lab_automatizado.workers (
  worker_id text primary key,
  status text not null default 'offline' check (status in ('online', 'busy', 'offline', 'degraded')),
  capabilities jsonb not null default '[]'::jsonb,
  version text,
  last_heartbeat_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists runs_status_created_idx
  on lab_automatizado.runs (status, created_at desc);

create index if not exists commands_queue_idx
  on lab_automatizado.commands (status, requested_at);

create index if not exists events_run_created_idx
  on lab_automatizado.events (run_id, created_at);

drop trigger if exists runs_set_updated_at on lab_automatizado.runs;
create trigger runs_set_updated_at
before update on lab_automatizado.runs
for each row execute function lab_automatizado.set_updated_at();

drop trigger if exists workers_set_updated_at on lab_automatizado.workers;
create trigger workers_set_updated_at
before update on lab_automatizado.workers
for each row execute function lab_automatizado.set_updated_at();

-- O painel e o worker usarão uma chave exclusivamente server-side.
-- Nenhum acesso público é liberado nesta primeira fase.
alter table lab_automatizado.runs enable row level security;
alter table lab_automatizado.commands enable row level security;
alter table lab_automatizado.events enable row level security;
alter table lab_automatizado.artifacts enable row level security;
alter table lab_automatizado.workers enable row level security;

revoke all on schema lab_automatizado from public, anon, authenticated;
revoke all on all tables in schema lab_automatizado from public, anon, authenticated;
grant usage on schema lab_automatizado to service_role;
grant select, insert, update, delete on all tables in schema lab_automatizado to service_role;
grant usage, select on all sequences in schema lab_automatizado to service_role;

comment on schema lab_automatizado is 'Control plane privado do Laboratório Automatizado; sem dados brutos de mercado.';
comment on table lab_automatizado.runs is 'Execuções declarativas e seus estados auditáveis.';
comment on table lab_automatizado.commands is 'Fila idempotente de comandos aceitos pelo worker.';
comment on table lab_automatizado.events is 'Log append-only de eventos de execução.';
comment on table lab_automatizado.artifacts is 'Referências e hashes de artefatos fora do Postgres.';
comment on table lab_automatizado.workers is 'Heartbeat e capacidades dos workers deste laboratório.';
